## 第012讲 找出所有能整除120的整数

### Problem 问题描述

Please write program to find all integers that can divide 120 with no remainder and put them into a list named `factors`. Print out the total number of the factors and check whether 24 is in the factors list.

请编写程序找出所有能整除120的整数并把他们存放到一个名为`factors`的列表型变量中。打印输出因数的总的数量，并检查24是否在列表中。

### Math Background 数学背景

1. **Factor** if the Q is the quotien of an integer A divided by another integer B, and the remainder is 0, we say that B is a factor of A; meanwhile, Q is also a factor of A. For example,$15\div3=5 \cdots 0$ we say both 3 and 5 are factors of the integer 15. It is obvious that any integer greather than 1 has at least two factors: 1 and the integer itself. It is also obvious that factors is always less then or equal to the integer.    
   **因数** 如果一个整数A除以另一个整数B，得到的商为Q且余数为0，那么称整数B为整数A的一个因数，同时商Q也是整数A的一个因数。例如，在除法算式：$15\div3=5 \cdots 0$中,被除数15除以除数3，商为5，余数为0，那么3和5都分别为15的一个因数。不难得出，任何一个比1大的整数都至少有两个因数，分别为1和它自己；同时也不难得出一个数的因数不可能比这个数大。
   
2. **Composite Number**: If an integer has an extra factor other than 1 and itself, this integer is a composite number.  
   **合数**: 如果一个整数除了1和自身还有其他额外的因数，那么这个整数是一个合数。
   
3. **Prime Number**: If an integer has only the two factors, it is called as a prime number.   
   **质数**: 如果一个整数只有1和它自身两个因数，那么它是一个质数。
   

### Prerequisites 预备知识

#### 1. Declare an empty（without any element）list variable 声明一个空（没有任何元素）的列表

In [22]:
classmates = []       # 同学： "Jason", "Tony", "Sophie", "Yunzi"
print(classmates)

[]


#### 2. add an element to (the end of) a list 往列表(最后）添加一个元素

The element of a list can be either an Integer or a String. It can even be many other data types， which we will learn in future.

列表的元素既可以是整数型数据，也可以是字符串型数据，还可以是将来要学习的其他一些类型的数据。

use `append` method add a string `"Sophie"` to the `classmates` list. `.` is an operator indicating that method `append` is applied on the list variable `classmates`. The method needs to receive an argument indicating the element that will be added into the tail of the list.

使用`append`方法往`classmates`列表中添加一个字符串`"Sophie"`, `.` 是一个操作符，表明方法`append`正应用在`classmates`这个列表型变量上。该方法需要接受那个将要被添加到列表末尾的元素作为参数。

In [23]:
classmates.append("Sophie")
print(classmates)

['Sophie']


Continue to add more students to the class

继续往班级同学列表里添加更多的学生

In [24]:
classmates.append("Tony")
print(classmates)

['Sophie', 'Tony']


In [25]:
classmates.append("Jason")
print(classmates)

['Sophie', 'Tony', 'Jason']


In [26]:
classmates.append("Yunzi")
print(classmates)

['Sophie', 'Tony', 'Jason', 'Yunzi']


In [27]:
classmates.append("Tony's Daddy")
print(classmates)

['Sophie', 'Tony', 'Jason', 'Yunzi', "Tony's Daddy"]


#### 2. remove an element from a list 从列表中删除一个元素

use `remove` method to remove "Yunzi's Daddy" from the `classmates` list. `remove` method need to receive an argument indicating the element value that need to be removed. If this value doesn't exist in the list, the program will report an error.

使用`remove`方法从`classmates`列表中移除`"Yunzi's Daddy"`. `remove`方法需要接受将要被删除出列表的那个元素的值，这个值如果在列表中不存在，那么程序会报错。

In [28]:
classmates.remove("Tony's Daddy")
print(classmates)

['Sophie', 'Tony', 'Jason', 'Yunzi']


In [29]:
classmates.remove("Sophie's Daddy")
print(classmates)

ValueError: list.remove(x): x not in list

#### 3. Exercise 练习

Declare an empty list variable with the name you prefer, put at least 5 names of the animals you like into the list one by one, then remove those animals that you have already seen in real life(not on TV or other video channels) from the list one by one, keey only those you like but haven't seen them face to face. Introduce these animals to your classmates.

用一个你喜欢的名字声明一个列表变量，往这个变量中一个接一个的添加至少5个你喜欢的动物，然后把在你已经亲眼见过(不是在电视或其他视频频道商）动物一个接一个的从列表中删除，只留下哪些你喜欢但还没有亲眼见过的动物们。向你的同学们介绍你列出的这些动物。

#### 4. check whether a value is in a list 检查一个值是否存在列表中

To check whether a value is in a list, or an element of the list, we can use a `while` loop to look at each element in the list, compare the values. If two values are same, then we can say the value is in the list, or the value is one of the element of the list. For example, the following codes check whether a string `"Jason"` is in the `classmates` list:

为了检查一个值是否在一个列表中，或者说是否是列表的一个元素，我们可以使用一个`while`循环来查看这个列表中的每一个元素，比较他们的值。如果两个值相同，那么我们就可以说这个值存在于这个列表中，或者说这个值是列表的一个元素。例如，要查看"Jason"是否在`classmates`列表中，我们可以使用下面的代码：

In [20]:
print(classmates)

NameError: name 'classmates' is not defined

In [33]:
target = "Jason"
index = 0
while index < len(classmates):
    print("checking value at index: {}".format(index))
    if target == classmates[index]:
        print("found target in the list, index is: {}".format(index)) 
    
    index += 1

checking value at index: 0
checking value at index: 1
checking value at index: 2
found target in the list, index is: 2
checking value at index: 3


#### 5. break(stop) the `while` loop when find the value 当找到值后打破（停止）循环

If the requirement is to only ask you to tell whether the value exists in the list, once you find one value which is equal to the target value, you can directly makde an positive statement, saying that the value is in the list. In this case, it is not necessary to look at all the other elements in the list. To break the loop, we can use `break` statement in our codes. Look at the following codes with a `break` statement added and compare the difference of the output with previous one:

如果要求仅仅是询问有一个值是否存在一个列表中，一旦我们在列表中发现这个元素，我们就可以作出肯定的判断，认为这个值存在于列表中。在这种情况下，就可以提前终止循环，没有必要再去检查列表中剩余没有看过的元素了。为了终止循环，我们可以在代码中添加一行`break`语句。请看下面加入了`break`语句的代码：

In [ ]:
target = "Jason"
index = 0
while index < len(classmates):
    print("checking value at index: {}".format(index))
    if target == classmates[index]:
        print("found target in the list, inde is: {}".format(index)) 
        break
        
    index += 1

#### 6. Another easy wat to check whether a value is in a list 另一个更简单的方式来检查一个值是否存在列表中

We can also use the keyword `in` to check wheter a value is in a list like following expression. If the result of the expression is `True`， it means a variable(value) is indeed in the list; if the expression result is `False`, it means the value is not an element of the list. When we execute this cell, it gives an output `True`, which means there is a value `"Tony"` in the `classmates` list.

我们也像下面的这行代码一样使用关键词`in`来检查一个变量（值）是否存在一个list中。如果表达式的值（输出）是`True`，则意味着要检查的变量（值）存在于列表中，反之则表示不存在。当我们执行下面的这行代码后，它会输出`True`，意味着`"Tony"`是列表`classmates`的一个元素。


In [ ]:
"Tony" in classmates

In [31]:
"Tony's Daddy" in classmates # None, false, False

False

In [ ]:
"jason" in classmates # False

In [ ]:
"Jason" in classmates # True

Since the above code is an expression that output either `True` or `False`, we can use it in a `if` condition code block like the following so that the programe prints out a more friendly output or complete some other tasks for each specific condition.

由于上面这行代码是一个输出结果要么是`True`要么是`False`的表达式，我们也可以像下面那样把它放在`if`引导的条件语句块中，让程序给出一个更友好的输出或者根据不同的条件完成一些额外的人物。

In [ ]:
if "Tony" in classmates:
    print("'Tony' is an element of classmates list")
else:
    print("'Tony' is not in the classmates list")

### Solution Codes 编程求解

Compare the two solutions, and tell the differences. How many loops have the programs expeirenced respectively? Can you make the loop tables for each solution?

比较两个解决方案，说出其中的差别。两个解决方案中的while循环各经历了几次循环？针对每一个解决方案，你能写出那个表示循环的表格吗？

In [ ]:
# Solution 1 解决方案1
target_num = 120           
num_checking = 1
factors = []
while num_checking <= target_num:
    if target_num % num_checking == 0:
        factors.append(num_checking)
    
    num_checking += 1
        
print("factors are: {}".format(factors))
print("{} factors".format(len(factors)))

element = 24
if element in factors:
    print("{} is in {}".format(element, factors))
else:
    print("{} is not in {}".format(element, factors))

In [ ]:
# Solution 2 解决方案2
target_num = 120           
num_checking = 1
quotien = target_num 

factors = []
while num_checking < quotien:
    if target_num % num_checking == 0:
        quotien = target_num // num_checking
        factors.append(num_checking)
        factors.append(quotien)
    
    num_checking += 1
        
print("factors are: {}".format(factors))
print("{} factors".format(len(factors)))

element = 24
if element in factors:
    print("{} is in {}".format(element, factors))
else:
    print("{} is not in {}".format(element, factors))

In [ ]:
print(120 // 4)
print(120 % 4)

In [ ]:
print(120 //30 )
print(120 % 30)

### Summary 知识点小结

- 学习操作列表型变量两个常见的方法`append`和`remove`
- 列表变量的元素可以是整数类型，也可以是字符串类型，还可以是其它类型
- 如何判断一个变量（值）是否存在于一个list中：使用while循环或使用关键词`in`
- `break`提前终止循环
- 复习列表型变量的`len`方法

### 计算机小知识

- 暂缺

### Assignments 作业

1. create an empty list with the variable name `my_friends`, use `append` method to add at least 5 of your friend names to this list, then use the method `remove` to remove one or several of your friend names from the list. Each time after you add or remove a friend name, print out the whole `my_friends` list and its length.  

   创建一个空的列表，变量名设为`my_friends`，使用`append`方法往这个列表里添加至少5个你的朋友名字，随后再使用`remove`方法从中移除一个或多个朋友名字。每一次当你使用`append`或`remove`方法后，都将整个`my_friends`列表的内容以及列表的长度打印出来。

In [30]:
my_friends = []
print(my_friends)

my_friends.append("Yolanda")
print(my_friends)

my_friends.append("Yiko")
print(my_friends)

my_friends.append("Makenzie")
print(my_friends)

my_friends.append("Lucille")
print(my_friends)

my_friends.append("Olie")
print(my_friends)

my_friends.remove("Makenzie")
print(my_friends)

my_friends.remove("Olie")
print(my_friends)

my_friends.remove("Lucille")
print(my_friends)

[]
['Yolanda']
['Yolanda', 'Yiko']
['Yolanda', 'Yiko', 'Makenzie']
['Yolanda', 'Yiko', 'Makenzie', 'Lucille']
['Yolanda', 'Yiko', 'Makenzie', 'Lucille', 'Olie']
['Yolanda', 'Yiko', 'Lucille', 'Olie']
['Yolanda', 'Yiko', 'Lucille']
['Yolanda', 'Yiko']


2. Write a program to find all factors of 144 and 385, put their factors in to two lists, one is for 144, and the other is for 385. Print out the two lists and also tell which integer has more factors.  

   编写程序分别查找整数144和385各自的因数，把他们分别放到两个不同的列表中，编程输出这两个列表并输出谁的因数数量多

In [23]:
num1, num2 = 144, 385
factors1, factors2 = [], []
num_check = 1


#TODO: write codes to answer the question.
#      编写你的代码来回答本题。
while num_check <= num1:
    #print("number 144's factors")
    if num1 % num_check == 0:
        factors1.append(num_check)
    num_check += 1
num_check = 1
while num_check <= num2:
    #print("number 385's factors")
    if num2 % num_check == 0:
        factors2.append(num_check)
    num_check += 1

#print("number 144's factors")
print(factors1)

#print("number 385's factors")
print(factors2)

print("{} 的因数是 {}, 个数是 {}".format(num1, factors1, len(factors1)))
print("{} 的因数是 {}, 个数是 {}".format(num2, factors2, len(factors2)))
if len(factors1) > len(factors2):
    print("{} 的因数个数多于{}的因数个数".format(num1, num2))
else:
    print("{} 的因数个数少于或等于{}的因数个数".format(num1, num2))

[1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 36, 48, 72, 144]
[1, 5, 7, 11, 35, 55, 77, 385]
144 的因数是 [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 36, 48, 72, 144], 个数是 15
385 的因数是 [1, 5, 7, 11, 35, 55, 77, 385], 个数是 8
144 的因数个数多于385的因数个数


3. Following the previous question. After you have two lists for the factors of 144 and 385, Write a program to check if these two integers shared some factors, If yes, print out the shared factor(s).
   
   续前一题。 当你找到144和385的所有因数后，编写程序检查这两个数除了整数1以外还有没有共同的因数

#### factors_for_144 = [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 36, 48, 72, 144] # TODO: fill the factors of 144 into [], 把144的因数放到[]里
factors_for_385 = [1, 5, 7, 11, 35, 55, 77, 385] # TODO: fill the factors of 144 into [], 把144的因数放到[]里
i1 = len(factors_for_144)
i2 = len(factors_for_385)
i = 1
shared_factors = []
#TODO: write codes to answer the question.
#      编写你的代码来回答本题。

while i < i1:
    num = factors_for_144[i]
    print("checking {}".format(num))
    if num in factors_for_385:
        shared_factors.append(num)
    
    i += 1
    
yes_or_no = len(shared_factors)
if yes_or_no == 0:
    print("there is no shared factors betwene 144 and 385.")
else:
    print("there is some shared factors betwene 144 and 385.")
print("shared factors list:", shared_factors)

4. if an integer only have two factors(1 and the integer itself), this integer is a Prime number; Otherwise, it is a Composite number. Write a program to find all the prime and composite numbers between 2 and 100 (both included). Use two lists to store all these prime and composite numbers. Finally, print out the two lists.

   
   如果一个整数的因数个数为2个（整数1和它自己），那么这个整数为“质数”，否则这个数则为合数。编写程序找出从2-100这100个连续整数中哪些是质数，哪些是合数，分别用两个列表来存储质数和合数，并最后将其打印出来。

In [4]:
num_start, num_end = 2, 100
list_prime = []
list_composite = []
num_check = num_start
i = 2
d1 = 2
d2 = 3
d3 = 5
d4 = 11

# TODO: Add your codes here
while i >= num_start and i <= num_end:
    r1 = num_check % d1
    r2 = num_check % d2
    r3 = num_check % d3
    r4 = num_check % d4
    
    if r1 == 0 or r2 == 0 or r3 == 0 or r4 == 0:
        list_composite.append(num_check)
    
    else:
        list_prime.append(num_check)
    num_check += 1
    i += 1

print("Prime numbers: {}".format(list_prime))
print("Composite numbers: {}".format(list_composite))

Prime numbers: [7, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59, 61, 67, 71, 73, 79, 83, 89, 91, 97]
Composite numbers: [2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 38, 39, 40, 42, 44, 45, 46, 48, 50, 51, 52, 54, 55, 56, 57, 58, 60, 62, 63, 64, 65, 66, 68, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 90, 92, 93, 94, 95, 96, 98, 99, 100]


In [43]:
list_prime = [7, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59, 61, 67, 71, 73, 79, 83, 89, 91, 97]
i = 1
index = 0
max_num = 23
while i <= max_num:
    num = list_prime[index]
    if num % 2 == 0:
        print("{} is composite".format(num))
    else:
        print("{} is prime".format(num))
    index += 1
    i += 1

7 is prime
13 is prime
17 is prime
19 is prime
23 is prime
29 is prime
31 is prime
37 is prime
41 is prime
43 is prime
47 is prime
49 is prime
53 is prime
59 is prime
61 is prime
67 is prime
71 is prime
73 is prime
79 is prime
83 is prime
89 is prime
91 is prime
97 is prime


5. The following list `list_a` has 2 elements, both of which are integer `1`. Please write a program to add 20 more new elements to the end of `list_a` step by step while respecting the following rule: **every time when you add a new element to the end of the list, its value is the sum of the values of the last two elements in the list.** Print out the final list when you finish adding elements. The final list you get should have 22 elements with `17711` as its last element. Are your familiar with the first 10 element in this list?

   下面名为`list_a`的列表一开始有2个元素且值均为`1`。请编写程序往这个列表的末端逐次再添加20个新元素，**要求每次新添加的元素值是当时列表的最末两位元素的值的和。** 添加完毕后打印输出这个列表。你最后得到的列表应该具有22个元素，且最后一个元素的值为`17711`。你熟悉这个列表的前10个元素吗？

In [19]:
list_a = [1, 1]
list_max_num = 21
list_num_now = len(list_a)
need_num1 = 1
need_num2 = 1


#TODO: write codes to answer the question.
#      编写你的代码来回答本题
while list_num_now <= list_max_num:
    #num = list_a[need_num1] + list_a[need_num2]
    num = need_num1 + need_num2
    list_a.append(num)
    list_num_now += 1
    need_num1 = need_num2
    need_num2 = num
    
    print(list_a)
    print("num = {}, the list long is {}, need_num1 = {} and need_num2 = {}"\
    .format(num, list_num_now, need_num1, need_num2))

print(len(list_a))
if len(list_a) != 22 or list_a[-1] != 17711:
    print("your answer is not correct")
else:
    print("your answer is correct")
    print(list_a)


[1, 1, 2]
num = 2, the list long is 3, need_num1 = 1 and need_num2 = 2
[1, 1, 2, 3]
num = 3, the list long is 4, need_num1 = 2 and need_num2 = 3
[1, 1, 2, 3, 5]
num = 5, the list long is 5, need_num1 = 3 and need_num2 = 5
[1, 1, 2, 3, 5, 8]
num = 8, the list long is 6, need_num1 = 5 and need_num2 = 8
[1, 1, 2, 3, 5, 8, 13]
num = 13, the list long is 7, need_num1 = 8 and need_num2 = 13
[1, 1, 2, 3, 5, 8, 13, 21]
num = 21, the list long is 8, need_num1 = 13 and need_num2 = 21
[1, 1, 2, 3, 5, 8, 13, 21, 34]
num = 34, the list long is 9, need_num1 = 21 and need_num2 = 34
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
num = 55, the list long is 10, need_num1 = 34 and need_num2 = 55
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
num = 89, the list long is 11, need_num1 = 55 and need_num2 = 89
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]
num = 144, the list long is 12, need_num1 = 89 and need_num2 = 144
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
num = 233, the list long is 13, need_num1 = 144 and need_num2 

In [44]:
list_a = [1, 1]
list_max_num = 20
list_num_now = 0
need_num1 = 0
need_num2 = 1